project:
  type: website

website:
  title: "MW"
  favicon: images/favicon.png
  image: images/banner.png
  site-url: https://maximilian-weichart.de
  open-graph: true
  twitter-card: true
  navbar:
    logo: images/favicon.png
    right:
      - about.qmd
      - icon: github
        href: https://github.com/Max-We
        aria-label: GitHub

format:
  html:
    theme: litera
    css: styles.css

execute:
  freeze: auto
